server:
  port:  1316
spring:
   application:
              name: feing-client
eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka
feign:
    hystrix:
        enabled: true

