server:
  port: 1314
spring:
    application:
              name:   sayhello
client:
   serviceUrl:
      defaultZone: http://peer1:8761/eureka

---
 server:
   port: 1313
 spring:
     application:
               name:   sayhello
 client:
    serviceUrl:
       defaultZone: http://peer1:8761/eureka